# Templates de prompts pour MusicGen

# Recherche sur les prompts efficaces pour MusicGen
MUSICGEN_TEMPLATES = {
    "techno_kick": "A deep, punchy techno kick drum pattern with {tempo} BPM, minimal and driving, clean low end, perfect for mixing, no melody, just rhythm section, {style_tag}",
    "techno_bass": "A dark techno bassline at {tempo} BPM, hypnotic and repetitive with subtle variations, in key {key}, minimal elements, {style_tag}",
    "techno_synth": "A minimal techno synth pad at {tempo} BPM, atmospheric and hypnotic, in key {key}, subtle and evolving texture, {style_tag}",
    "techno_percussion": "Techno percussion loop at {tempo} BPM, crisp hi-hats and claps, no kick drum, just tops, minimal techno style, {style_tag}",
    "techno_fx": "Abstract techno sound effect, atmospheric and spatial, suitable for transitions in a {tempo} BPM techno track, {style_tag}",
}

# Paramètres spécifiques pour chaque type de sample
SAMPLE_PARAMS = {
    "techno_kick": {
        "duration": 8,  # 8 secondes = typiquement 4 mesures à 120 BPM
        "should_start_with_kick": True,
        "key_sensitive": False,
    },
    "techno_bass": {
        "duration": 8,
        "should_start_with_kick": False,
        "key_sensitive": True,
    },
    "techno_synth": {
        "duration": 16,  # Plus long pour les pads atmosphériques
        "should_start_with_kick": False,
        "key_sensitive": True,
    },
    "techno_percussion": {
        "duration": 8,
        "should_start_with_kick": False,
        "key_sensitive": False,
    },
    "techno_fx": {
        "duration": 4,
        "should_start_with_kick": False,
        "key_sensitive": False,
    },
}

rhythm_types = [
    # Techno/Electronic
    "techno_kick",
    "techno_percussion",
    "techno_drums",
    "techno_beat",
    "electronic_drums",
    "electronic_percussion",
    "electro_beat",
    "techno_loop",
    "minimal_beat",
    "minimal_drums",
    "minimal_percussion",
    "acid_percussion",
    "industrial_drums",
    # House
    "house_kick",
    "house_percussion",
    "house_drums",
    "house_beat",
    "house_rhythm",
    "deep_house_drums",
    "deep_house_percussion",
    "deep_house_kick",
    "deep_house_rhythm",
    "soulful_house_drums",
    "jazzy_house_percussion",
    "progressive_house_beat",
    "tech_house_percussion",
    "tech_house_kick",
    "afro_house_percussion",
    "tribal_house_drums",
    "chicago_house_beat",
    "disco_house_rhythm",
    # Hip-Hop
    "hiphop_beat",
    "hip_hop_beat",
    "hiphop_drums",
    "trap_beat",
    "boom_bap_beat",
    "hiphop_percussion",
    "lo-fi_beat",
    "lo-fi_drums",
    "rap_beat",
    "urban_drums",
    "808_beat",
    "breakbeat",
    "beat_loop",
    "drill_beat",
    "crunk_drums",
    "phonk_rhythm",
    "old_school_beat",
    "dirty_south_drums",
    # Rock
    "rock_drums",
    "rock_beat",
    "rock_percussion",
    "indie_drums",
    "alternative_beat",
    "drum_kit",
    "live_drums",
    "acoustic_drums",
    "band_percussion",
    "metal_drums",
    "punk_beat",
    "progressive_rock_drums",
    "psychedelic_percussion",
    "garage_rock_beat",
    # Général
    "drum_loop",
    "percussion_loop",
    "beat_pattern",
    "rhythm_section",
    "groove_loop",
    "drum_pattern",
    "rhythm_loop",
    "percussion_pattern",
    "beat_section",
    "metronome",
    "click_track",
    "polyrhythm_loop",
    # Styles spécifiques
    "glitch_perc",
    "glitch_drums",
    "experimental_percussion",
    "abstract_beat",
    "jungle_drums",
    "dnb_beat",
    "breakcore_drums",
    "ambient_percussion",
    "industrial_beat",
    "noise_rhythm",
    "footwork_beat",
    "juke_drums",
    "uk_garage_beat",
    "2step_rhythm",
    "grime_drums",
    "dubstep_beat",
    "future_garage_rhythm",
    "neuro_drums",
    "liquid_breaks",
    # Dub/Reggae
    "dub_riddim",
    "dub_drums",
    "dub_percussion",
    "dub_beat",
    "dub_steppers",
    "reggae_riddim",
    "reggae_drums",
    "reggae_percussion",
    "steppers_beat",
    "one_drop_drums",
    "rockers_rhythm",
    "nyabinghi_drums",
    "roots_percussion",
    "dub_echo_drums",
    "dub_one_drop",
    "dancehall_beat",
    "roots_beat",
    "ska_drums",
    "rocksteady_rhythm",
    # Deep House Spécifique
    "deep_house_beat",
    "jazzy_house_drums",
    "soulful_rhythm",
    "organic_house_percussion",
    "lounge_house_beat",
    "afro_deep_percussion",
    "nu_jazz_drums",
    "downtempo_house_beat",
    "spiritual_house_percussion",
    "mellow_house_rhythm",
    "detroit_house_beat",
    "rhodes_house_groove",
    # Autres Genres
    "trance_percussion",
    "hardstyle_kick",
    "gabber_drums",
    "hardcore_beat",
    "psytrance_rhythm",
    "goa_beat",
    "idm_drums",
    "ambient_beat",
    "downtempo_rhythm",
    "trip_hop_drums",
    "chillout_percussion",
    "balearic_rhythm",
    "latin_percussion",
    "afrobeat_drums",
    "world_percussion",
    "fusion_rhythm",
    "cinematic_drums",
    "orchestral_percussion",
    "big_band_drums",
    "jazz_rhythm",
    "funk_beat",
    "soul_groove",
    "disco_beat",
    "vaporwave_drums",
    "synthwave_percussion",
    "8bit_beat",  # Dans la liste rhythm_types, ajouter:
    "triphop_beat",
    "triphop_drums",
    "triphop_percussion",
    "triphop_rhythm",
    "broken_beat",
    "vinyl_drums",
    "scratchy_beat",
]

# Liste étendue des mots-clés qui suggèrent un élément rythmique
rhythm_keywords = [
    # Éléments de batterie
    "kick",
    "drum",
    "snare",
    "hat",
    "hihat",
    "hi-hat",
    "cymbal",
    "clap",
    "rim",
    "tom",
    "conga",
    "bongo",
    "shaker",
    "tambourine",
    "cowbell",
    "woodblock",
    "ride",
    "crash",
    "stick",
    "brushes",
    "clave",
    "timbale",
    "djembe",
    "tabla",
    "cajon",
    "guiro",
    "maracas",
    # Types de patterns
    "beat",
    "rhythm",
    "groove",
    "percussion",
    "loop",
    "break",
    "pattern",
    "fill",
    "shuffle",
    "swing",
    "cadence",
    "pulse",
    "meter",
    "measure",
    "downbeat",
    "upbeat",
    "backbeat",
    "accent",
    "ghost note",
    "syncopation",
    # Descriptions spécifiques
    "808",
    "909",
    "606",
    "707",
    "727",
    "LinnDrum",
    "DMX",
    "kit",
    "top",
    "backbeat",
    "downbeat",
    "bpm",
    "tempo",
    "rolls",
    "flam",
    "paradiddle",
    "drag",
    "rimshot",
    "sidestick",
    "cross-stick",
    # Technologies/terminologie
    "sequenced",
    "programmed",
    "quantized",
    "acoustic",
    "electronic",
    "sampled",
    "live",
    "triggered",
    "MIDI",
    "velocity",
    "dynamic",
    "transient",
    "attack",
    "decay",
    "sustain",
    "release",
    "envelope",
    "modulation",
    "automation",
    # Styles rythmiques
    "four-on-floor",
    "breakbeat",
    "footwork",
    "swing",
    "shuffle",
    "trap",
    "boom-bap",
    "jungle",
    "dubstep",
    "step",
    "riddim",
    "polyrhythm",
    "syncopated",
    "riddim",
    "steppers",
    "one_drop",
    "rockers",
    "nyabinghi",
    "skank",
    "bubble",
    "roots",
    "dembow",
    "clave",
    "son",
    "tresillo",
    "cinquillo",
    # Deep House Spécifique
    "jazzy",
    "soulful",
    "organic",
    "vinyl",
    "analogue",
    "analog",
    "dusty",
    "lofi",
    "warm",
    "mellow",
    "smooth",
    "rhodes",
    "finger_snap",
    "brushed",
    "subtle",
    "gentle",
    "crisp",
    "tight",
    # Autres termes rythmiques
    "metric",
    "compound",
    "simple",
    "triple",
    "duple",
    "quadruple",
    "half-time",
    "double-time",
    "off-beat",
    "on-beat",
    "drop",
    "build",
    "breakdown",
    "build-up",
    "crescendo",
    "diminuendo",
    "cross-rhythm",
    "polymeter",
    "hemiola",
    "isorhythm",
    "ostinato",
    "groove",
    "pocket",
    "time-feel",
    "timing",
    "micro-timing",
    "humanized",
    "machine",
    "robotic",
    "tribal",
    "ethnic",
    "world",
    "fusion",
]
